<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\MultiDesk.Application\MultiDesk.Application.csproj" />
    <ProjectReference Include="..\MultiDesk.Infrastructure\MultiDesk.Infrastructure.csproj" />
    <ProjectReference Include="..\MultiDesk.Domain\MultiDesk.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
